package algz.eulerproject;

import java.math.BigDecimal;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class T2 {
    public BigDecimal fib() {
        BigDecimal sum = new BigDecimal(0);
        long f1 = 1;
        long f2 = 2;
        long f = f1+f2;
        while (f1 < 4000000) {
            f1 = f2;
            f2 = f;
            f = f1 + f2;

            //you can also use that fib numbers are placed like O, O, E, O, O, E...
            if (f1 % 2 == 0) {
                sum = sum.add(new BigDecimal(f1));
            }
        }
        return sum;
    }
}
